//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ServiceMessagesType", Namespace="http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0")]
    public partial class ServiceMessagesType1
    {
        
        private SeverityType1 highestSeverityField;
        
        private ServiceMessageType1[] serviceMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SeverityType1 highestSeverity
        {
            get
            {
                return this.highestSeverityField;
            }
            set
            {
                this.highestSeverityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceMessage", Order=1)]
        public ServiceMessageType1[] serviceMessage
        {
            get
            {
                return this.serviceMessageField;
            }
            set
            {
                this.serviceMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SeverityType", Namespace="http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreDatatypes/3.0")]
    public enum SeverityType1
    {
        
        /// <remarks/>
        Fatal,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Informational,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ServiceMessageType", Namespace="http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0")]
    public partial class ServiceMessageType1
    {
        
        private string codeField;
        
        private SeverityType1 severityField;
        
        private string reasonField;
        
        private detail1 detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SeverityType1 severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public detail1 details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="detail", Namespace="http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0")]
    public partial class detail1
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/elements")]
    public partial class detail
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/elements")]
    public partial class ServiceMessageType
    {
        
        private string codeField;
        
        private SeverityType severityField;
        
        private string reasonField;
        
        private detail detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SeverityType severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public detail details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/datatypes")]
    public enum SeverityType
    {
        
        /// <remarks/>
        Fatal,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Informational,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/elements")]
    public partial class ServiceMessagesType
    {
        
        private SeverityType highestSeverityField;
        
        private ServiceMessageType[] serviceMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SeverityType highestSeverity
        {
            get
            {
                return this.highestSeverityField;
            }
            set
            {
                this.highestSeverityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceMessage", Order=1)]
        public ServiceMessageType[] serviceMessage
        {
            get
            {
                return this.serviceMessageField;
            }
            set
            {
                this.serviceMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.provider.gov.au/match/schema/2018/04/14/elements")]
    public partial class MatchProviderAdministrativeIndividualResponseType
    {
        
        private IdentifierType identifierField;
        
        private bool matchedFlagField;
        
        private ServiceMessagesType[] serviceMessagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdentifierType identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool matchedFlag
        {
            get
            {
                return this.matchedFlagField;
            }
            set
            {
                this.matchedFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceMessages", Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/elements", Order=2)]
        public ServiceMessagesType[] serviceMessages
        {
            get
            {
                return this.serviceMessagesField;
            }
            set
            {
                this.serviceMessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.provider.gov.au/match/schema/2018/04/14/types")]
    public partial class IdentifierType
    {
        
        private string valueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.provider.gov.au/match/schema/2018/04/14/types")]
    public partial class PersonalNameDetailsType
    {
        
        private string[] givenNameField;
        
        private string familyNameField;
        
        private string genderField;
        
        private bool currentFlagField;
        
        private bool currentFlagFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("givenName", Order=0)]
        public string[] givenName
        {
            get
            {
                return this.givenNameField;
            }
            set
            {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string familyName
        {
            get
            {
                return this.familyNameField;
            }
            set
            {
                this.familyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool currentFlag
        {
            get
            {
                return this.currentFlagField;
            }
            set
            {
                this.currentFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentFlagSpecified
        {
            get
            {
                return this.currentFlagFieldSpecified;
            }
            set
            {
                this.currentFlagFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.provider.gov.au/match/schema/2018/04/14/types")]
    public partial class PersonalDetailsType
    {
        
        private System.DateTime dateOfBirthField;
        
        private bool dateOfBirthFieldSpecified;
        
        private PersonalNameDetailsType[] personalNameDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime dateOfBirth
        {
            get
            {
                return this.dateOfBirthField;
            }
            set
            {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateOfBirthSpecified
        {
            get
            {
                return this.dateOfBirthFieldSpecified;
            }
            set
            {
                this.dateOfBirthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("personalNameDetails", Order=1)]
        public PersonalNameDetailsType[] personalNameDetails
        {
            get
            {
                return this.personalNameDetailsField;
            }
            set
            {
                this.personalNameDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.provider.gov.au/match/schema/2018/04/14/elements")]
    public partial class MatchProviderAdministrativeIndividualRequestType
    {
        
        private IdentifierType relyingPartyIdentifierField;
        
        private IdentifierType hiServiceIdentifierField;
        
        private string requiredIdentifierTypeField;
        
        private PersonalDetailsType personalDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdentifierType relyingPartyIdentifier
        {
            get
            {
                return this.relyingPartyIdentifierField;
            }
            set
            {
                this.relyingPartyIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IdentifierType hiServiceIdentifier
        {
            get
            {
                return this.hiServiceIdentifierField;
            }
            set
            {
                this.hiServiceIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string requiredIdentifierType
        {
            get
            {
                return this.requiredIdentifierTypeField;
            }
            set
            {
                this.requiredIdentifierTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public PersonalDetailsType personalDetails
        {
            get
            {
                return this.personalDetailsField;
            }
            set
            {
                this.personalDetailsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ns.humanservices.gov.au/ehp/virtual/wsdl/matchservice/2018/04/14", ConfigurationName="nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministra" +
        "tiveIndividualVirtualPortType")]
    public interface MatchProviderAdministrativeIndividualVirtualPortType
    {
        
        // CODEGEN: Generating message contract since the operation matchProviderAdministrativeInd is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ns.humanservices.gov.au/ehp/virtual/svc/2018/04/14/matchProviderAdminIndiv" +
            "idualRequest", ReplyAction="http://ns.humanservices.gov.au/ehp/virtual/svc/2018/04/14/matchProviderAdminIndiv" +
            "idualResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.ServiceMessagesType1), Action="http://ns.humanservices.gov.au/dhs/svc/commonmessages/2011/07/01/standardfault", Name="serviceMessages", Namespace="http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualResponse matchProviderAdministrativeInd(nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ns.humanservices.gov.au/ehp/virtual/svc/2018/04/14/matchProviderAdminIndiv" +
            "idualRequest", ReplyAction="http://ns.humanservices.gov.au/ehp/virtual/svc/2018/04/14/matchProviderAdminIndiv" +
            "idualResponse")]
        System.Threading.Tasks.Task<nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualResponse> matchProviderAdministrativeIndAsync(nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.electronichealth.net.au/hi/xsd/common/QualifiedIdentifier/3.0")]
    public partial class QualifiedId
    {
        
        private string qualifierField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=0)]
        public string qualifier
        {
            get
            {
                return this.qualifierField;
            }
            set
            {
                this.qualifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0")]
    public partial class ProductType
    {
        
        private QualifiedId vendorField;
        
        private string productNameField;
        
        private string productVersionField;
        
        private string platformField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public QualifiedId vendor
        {
            get
            {
                return this.vendorField;
            }
            set
            {
                this.vendorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string productName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string productVersion
        {
            get
            {
                return this.productVersionField;
            }
            set
            {
                this.productVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string platform
        {
            get
            {
                return this.platformField;
            }
            set
            {
                this.platformField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0")]
    public partial class TimestampType
    {
        
        private System.DateTime createdField;
        
        private System.DateTime expiresField;
        
        private bool expiresFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime expires
        {
            get
            {
                return this.expiresField;
            }
            set
            {
                this.expiresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiresSpecified
        {
            get
            {
                return this.expiresFieldSpecified;
            }
            set
            {
                this.expiresFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    public partial class SecurityHeaderType
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class matchProviderAdministrativeIndividualRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0")]
        public nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.QualifiedId user;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0")]
        public nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.ProductType product;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0")]
        public nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.TimestampType timestamp;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.SecurityHeaderType Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="matchProviderAdministrativeIndividualRequest", Namespace="http://ns.provider.gov.au/match/schema/2018/04/14/elements", Order=0)]
        public nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualRequestType matchProviderAdministrativeIndividualRequest1;
        
        public matchProviderAdministrativeIndividualRequest()
        {
        }
        
        public matchProviderAdministrativeIndividualRequest(nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.QualifiedId user, nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.ProductType product, nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.TimestampType timestamp, nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.SecurityHeaderType Security, nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualRequestType matchProviderAdministrativeIndividualRequest1)
        {
            this.user = user;
            this.product = product;
            this.timestamp = timestamp;
            this.Security = Security;
            this.matchProviderAdministrativeIndividualRequest1 = matchProviderAdministrativeIndividualRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class matchProviderAdministrativeIndividualResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ns.electronichealth.net.au/hi/xsd/common/CommonCoreElements/3.0")]
        public nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.ProductType product;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.SecurityHeaderType Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="matchProviderAdministrativeIndividualResponse", Namespace="http://ns.provider.gov.au/match/schema/2018/04/14/elements", Order=0)]
        public nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualResponseType matchProviderAdministrativeIndividualResponse1;
        
        public matchProviderAdministrativeIndividualResponse()
        {
        }
        
        public matchProviderAdministrativeIndividualResponse(nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.ProductType product, nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.SecurityHeaderType Security, nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualResponseType matchProviderAdministrativeIndividualResponse1)
        {
            this.product = product;
            this.Security = Security;
            this.matchProviderAdministrativeIndividualResponse1 = matchProviderAdministrativeIndividualResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface MatchProviderAdministrativeIndividualVirtualPortTypeChannel : nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualVirtualPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class MatchProviderAdministrativeIndividualVirtualPortTypeClient : System.ServiceModel.ClientBase<nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualVirtualPortType>, nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualVirtualPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MatchProviderAdministrativeIndividualVirtualPortTypeClient() : 
                base(MatchProviderAdministrativeIndividualVirtualPortTypeClient.GetDefaultBinding(), MatchProviderAdministrativeIndividualVirtualPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MatchProviderAdministrativeIndividualPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MatchProviderAdministrativeIndividualVirtualPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(MatchProviderAdministrativeIndividualVirtualPortTypeClient.GetBindingForEndpoint(endpointConfiguration), MatchProviderAdministrativeIndividualVirtualPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MatchProviderAdministrativeIndividualVirtualPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MatchProviderAdministrativeIndividualVirtualPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MatchProviderAdministrativeIndividualVirtualPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MatchProviderAdministrativeIndividualVirtualPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MatchProviderAdministrativeIndividualVirtualPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualResponse nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualVirtualPortType.matchProviderAdministrativeInd(nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualRequest request)
        {
            return base.Channel.matchProviderAdministrativeInd(request);
        }
        
        public nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualResponseType matchProviderAdministrativeInd(nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.QualifiedId user, ref nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.ProductType product, nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.TimestampType timestamp, ref nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.SecurityHeaderType Security, nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualRequestType matchProviderAdministrativeIndividualRequest1)
        {
            nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualRequest inValue = new nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualRequest();
            inValue.user = user;
            inValue.product = product;
            inValue.timestamp = timestamp;
            inValue.Security = Security;
            inValue.matchProviderAdministrativeIndividualRequest1 = matchProviderAdministrativeIndividualRequest1;
            nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualResponse retVal = ((nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualVirtualPortType)(this)).matchProviderAdministrativeInd(inValue);
            product = retVal.product;
            Security = retVal.Security;
            return retVal.matchProviderAdministrativeIndividualResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualResponse> nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualVirtualPortType.matchProviderAdministrativeIndAsync(nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualRequest request)
        {
            return base.Channel.matchProviderAdministrativeIndAsync(request);
        }
        
        public System.Threading.Tasks.Task<nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualResponse> matchProviderAdministrativeIndAsync(nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.QualifiedId user, nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.ProductType product, nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.TimestampType timestamp, nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.SecurityHeaderType Security, nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualRequestType matchProviderAdministrativeIndividualRequest1)
        {
            nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualRequest inValue = new nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualRequest();
            inValue.user = user;
            inValue.product = product;
            inValue.timestamp = timestamp;
            inValue.Security = Security;
            inValue.matchProviderAdministrativeIndividualRequest1 = matchProviderAdministrativeIndividualRequest1;
            return ((nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualVirtualPortType)(this)).matchProviderAdministrativeIndAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MatchProviderAdministrativeIndividualPort))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MatchProviderAdministrativeIndividualPort))
            {
                return new System.ServiceModel.EndpointAddress("http://humanservices.gov.au/dhs/pcehr/matchservice/virtual/endpoint/2018/04/14");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MatchProviderAdministrativeIndividualVirtualPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.MatchProviderAdministrativeIndividualPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MatchProviderAdministrativeIndividualVirtualPortTypeClient.GetEndpointAddress(EndpointConfiguration.MatchProviderAdministrativeIndividualPort);
        }
        
        public enum EndpointConfiguration
        {
            
            MatchProviderAdministrativeIndividualPort,
        }
    }
}
