//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/elements")]
    public partial class ServiceMessagesType
    {
        
        private SeverityType highestSeverityField;
        
        private ServiceMessageType[] serviceMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SeverityType highestSeverity
        {
            get
            {
                return this.highestSeverityField;
            }
            set
            {
                this.highestSeverityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceMessage", Order=1)]
        public ServiceMessageType[] serviceMessage
        {
            get
            {
                return this.serviceMessageField;
            }
            set
            {
                this.serviceMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/datatypes")]
    public enum SeverityType
    {
        
        /// <remarks/>
        Fatal,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Informational,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/elements")]
    public partial class ServiceMessageType
    {
        
        private string codeField;
        
        private SeverityType severityField;
        
        private string reasonField;
        
        private detail detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SeverityType severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public detail details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/elements")]
    public partial class detail
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.provider.gov.au/match/schema/2018/04/14/elements")]
    public partial class MatchProviderAdministrativeIndividualResponseType
    {
        
        private IdentifierType identifierField;
        
        private bool matchedFlagField;
        
        private ServiceMessagesType[] serviceMessagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdentifierType identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool matchedFlag
        {
            get
            {
                return this.matchedFlagField;
            }
            set
            {
                this.matchedFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("serviceMessages", Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/elements", Order=2)]
        public ServiceMessagesType[] serviceMessages
        {
            get
            {
                return this.serviceMessagesField;
            }
            set
            {
                this.serviceMessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.provider.gov.au/match/schema/2018/04/14/types")]
    public partial class IdentifierType
    {
        
        private string valueField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.provider.gov.au/match/schema/2018/04/14/types")]
    public partial class PersonalNameDetailsType
    {
        
        private string[] givenNameField;
        
        private string familyNameField;
        
        private string genderField;
        
        private bool currentFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("givenName", Order=0)]
        public string[] givenName
        {
            get
            {
                return this.givenNameField;
            }
            set
            {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string familyName
        {
            get
            {
                return this.familyNameField;
            }
            set
            {
                this.familyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool currentFlag
        {
            get
            {
                return this.currentFlagField;
            }
            set
            {
                this.currentFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.provider.gov.au/match/schema/2018/04/14/types")]
    public partial class PersonalDetailsType
    {
        
        private System.DateTime dateOfBirthField;
        
        private PersonalNameDetailsType[] personalNameDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime dateOfBirth
        {
            get
            {
                return this.dateOfBirthField;
            }
            set
            {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("personalNameDetails", Order=1)]
        public PersonalNameDetailsType[] personalNameDetails
        {
            get
            {
                return this.personalNameDetailsField;
            }
            set
            {
                this.personalNameDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.provider.gov.au/match/schema/2018/04/14/elements")]
    public partial class MatchProviderAdministrativeIndividualRequestType
    {
        
        private IdentifierType providedIdentifierField;
        
        private string requiredIdentifierTypeField;
        
        private PersonalDetailsType personalDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public IdentifierType providedIdentifier
        {
            get
            {
                return this.providedIdentifierField;
            }
            set
            {
                this.providedIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string requiredIdentifierType
        {
            get
            {
                return this.requiredIdentifierTypeField;
            }
            set
            {
                this.requiredIdentifierTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PersonalDetailsType personalDetails
        {
            get
            {
                return this.personalDetailsField;
            }
            set
            {
                this.personalDetailsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ns.provider.gov.au/internal/concrete/wsdl/matchservice/2018/04/14", ConfigurationName="nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministra" +
        "tiveIndividualPortType")]
    public interface MatchProviderAdministrativeIndividualPortType
    {
        
        // CODEGEN: Generating message contract since the operation matchProviderAdministrativeIndividual is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://ns.provider.gov.au/2018/04/14/matchProviderAdministrativeIndividualRequest" +
            "", ReplyAction="http://ns.provider.gov.au/2018/04/14/matchProviderAdministrativeIndividualRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.ServiceMessagesType), Action="http://ns.humanservices.gov.au/dhs/svc/commonmessages/2011/07/01/standardfault", Name="serviceMessages", Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/elements")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualResponse matchProviderAdministrativeIndividual(nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ns.provider.gov.au/2018/04/14/matchProviderAdministrativeIndividualRequest" +
            "", ReplyAction="http://ns.provider.gov.au/2018/04/14/matchProviderAdministrativeIndividualRespons" +
            "e")]
        System.Threading.Tasks.Task<nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualResponse> matchProviderAdministrativeIndividualAsync(nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    public partial class SecurityHeaderType
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.humanservices.gov.au/common/qualifiedidentifier/schema/2014/03/15")]
    public partial class QualifiedId
    {
        
        private string qualifierField;
        
        private string idField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=0)]
        public string qualifier
        {
            get
            {
                return this.qualifierField;
            }
            set
            {
                this.qualifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/elements")]
    public partial class AuditType
    {
        
        private AuditUserType userField;
        
        private string globalSessionKeyField;
        
        private NameValuePairType[] additionalDataField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AuditUserType user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string globalSessionKey
        {
            get
            {
                return this.globalSessionKeyField;
            }
            set
            {
                this.globalSessionKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("nameValuePair", IsNullable=false)]
        public NameValuePairType[] additionalData
        {
            get
            {
                return this.additionalDataField;
            }
            set
            {
                this.additionalDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/elements")]
    public partial class AuditUserType
    {
        
        private QualifiedId userIdField;
        
        private string userTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public QualifiedId userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string userType
        {
            get
            {
                return this.userTypeField;
            }
            set
            {
                this.userTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/elements")]
    public partial class NameValuePairType
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/elements")]
    public partial class ProductType
    {
        
        private QualifiedId organisationField;
        
        private string productNameField;
        
        private string productVersionField;
        
        private string platformField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public QualifiedId organisation
        {
            get
            {
                return this.organisationField;
            }
            set
            {
                this.organisationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string productName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string productVersion
        {
            get
            {
                return this.productVersionField;
            }
            set
            {
                this.productVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string platform
        {
            get
            {
                return this.platformField;
            }
            set
            {
                this.platformField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class AttributedURIType
    {
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class RelatesToType
    {
        
        private string relationshipTypeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        private string valueField;
        
        public RelatesToType()
        {
            this.relationshipTypeField = "http://www.w3.org/2005/08/addressing/reply";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("http://www.w3.org/2005/08/addressing/reply")]
        public string RelationshipType
        {
            get
            {
                return this.relationshipTypeField;
            }
            set
            {
                this.relationshipTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class matchProviderAdministrativeIndividualRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.SecurityHeaderType Security;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/elements")]
        public nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.QualifiedId subjectId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/elements")]
        public nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AuditType audit;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/elements")]
        public nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.ProductType product;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType Action;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType To;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType MessageID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="matchProviderAdministrativeIndividualRequest", Namespace="http://ns.provider.gov.au/match/schema/2018/04/14/elements", Order=0)]
        public nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualRequestType matchProviderAdministrativeIndividualRequest1;
        
        public matchProviderAdministrativeIndividualRequest()
        {
        }
        
        public matchProviderAdministrativeIndividualRequest(nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.SecurityHeaderType Security, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.QualifiedId subjectId, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AuditType audit, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.ProductType product, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType Action, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType To, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType MessageID, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualRequestType matchProviderAdministrativeIndividualRequest1)
        {
            this.Security = Security;
            this.subjectId = subjectId;
            this.audit = audit;
            this.product = product;
            this.Action = Action;
            this.To = To;
            this.MessageID = MessageID;
            this.matchProviderAdministrativeIndividualRequest1 = matchProviderAdministrativeIndividualRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class matchProviderAdministrativeIndividualResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://ns.humanservices.gov.au/common/schema/2014/03/15/elements")]
        public nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.ProductType product;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType Action;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType To;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType MessageID;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
        public nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.RelatesToType RelatesTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="matchProviderAdministrativeIndividualResponse", Namespace="http://ns.provider.gov.au/match/schema/2018/04/14/elements", Order=0)]
        public nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualResponseType matchProviderAdministrativeIndividualResponse1;
        
        public matchProviderAdministrativeIndividualResponse()
        {
        }
        
        public matchProviderAdministrativeIndividualResponse(nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.ProductType product, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType Action, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType To, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType MessageID, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.RelatesToType RelatesTo, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualResponseType matchProviderAdministrativeIndividualResponse1)
        {
            this.product = product;
            this.Action = Action;
            this.To = To;
            this.MessageID = MessageID;
            this.RelatesTo = RelatesTo;
            this.matchProviderAdministrativeIndividualResponse1 = matchProviderAdministrativeIndividualResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MatchProviderAdministrativeIndividualPortTypeChannel : nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchProviderAdministrativeIndividualPortTypeClient : System.ServiceModel.ClientBase<nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualPortType>, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualPortType
    {
        
        public MatchProviderAdministrativeIndividualPortTypeClient()
        {
        }
        
        public MatchProviderAdministrativeIndividualPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MatchProviderAdministrativeIndividualPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MatchProviderAdministrativeIndividualPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MatchProviderAdministrativeIndividualPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualResponse nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualPortType.matchProviderAdministrativeIndividual(nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualRequest request)
        {
            return base.Channel.matchProviderAdministrativeIndividual(request);
        }
        
        public nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.RelatesToType matchProviderAdministrativeIndividual(nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.SecurityHeaderType Security, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.QualifiedId subjectId, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AuditType audit, ref nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.ProductType product, ref nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType Action, ref nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType To, ref nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType MessageID, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualRequestType matchProviderAdministrativeIndividualRequest1, out nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualResponseType matchProviderAdministrativeIndividualResponse1)
        {
            nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualRequest inValue = new nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualRequest();
            inValue.Security = Security;
            inValue.subjectId = subjectId;
            inValue.audit = audit;
            inValue.product = product;
            inValue.Action = Action;
            inValue.To = To;
            inValue.MessageID = MessageID;
            inValue.matchProviderAdministrativeIndividualRequest1 = matchProviderAdministrativeIndividualRequest1;
            nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualResponse retVal = ((nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualPortType)(this)).matchProviderAdministrativeIndividual(inValue);
            product = retVal.product;
            Action = retVal.Action;
            To = retVal.To;
            MessageID = retVal.MessageID;
            matchProviderAdministrativeIndividualResponse1 = retVal.matchProviderAdministrativeIndividualResponse1;
            return retVal.RelatesTo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualResponse> nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualPortType.matchProviderAdministrativeIndividualAsync(nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualRequest request)
        {
            return base.Channel.matchProviderAdministrativeIndividualAsync(request);
        }
        
        public System.Threading.Tasks.Task<nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualResponse> matchProviderAdministrativeIndividualAsync(nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.SecurityHeaderType Security, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.QualifiedId subjectId, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AuditType audit, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.ProductType product, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType Action, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType To, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.AttributedURIType MessageID, nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualRequestType matchProviderAdministrativeIndividualRequest1)
        {
            nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualRequest inValue = new nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.matchProviderAdministrativeIndividualRequest();
            inValue.Security = Security;
            inValue.subjectId = subjectId;
            inValue.audit = audit;
            inValue.product = product;
            inValue.Action = Action;
            inValue.To = To;
            inValue.MessageID = MessageID;
            inValue.matchProviderAdministrativeIndividualRequest1 = matchProviderAdministrativeIndividualRequest1;
            return ((nehta.mcaR7.ProviderMatchProviderAdministrativeIndividual.MatchProviderAdministrativeIndividualPortType)(this)).matchProviderAdministrativeIndividualAsync(inValue);
        }
    }
}
