/*
 * Copyright 2011 NEHTA
 *
 * Licensed under the NEHTA Open Source (Apache) License; you may not use this
 * file except in compliance with the License. A copy of the License is in the
 * 'license.txt' file, which should be provided with this work.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

using System;
using System.Threading.Tasks;
using System.ServiceModel.Channels;
using System.Security.Cryptography.X509Certificates;
using System.ServiceModel;
using System.ServiceModel.Description;
using nehta.mcaR6.ProviderMatchProviderAdministrativeIndividual;
using Nehta.VendorLibrary.Common;

namespace Nehta.VendorLibrary.HI
{
    /// <summary>
    /// An implementation of a client for the Medicare Healthcare Identifiers service. This class may be used to 
    /// connect to Medicare's service to perform organisation searches, for provider information already
    /// published to the HPD.
    /// </summary>
    public class ProviderMatchProviderAdministrativeIndividualClient : IProviderMatchProviderAdministrativeIndividualClient
    {
        internal MatchProviderAdministrativeIndividualVirtualPortType providerMatchProviderAdministrativeIndividualClient;
                 
        /// <summary>
        /// SOAP messages for the last client call.
        /// </summary>
        public HIEndpointProcessor6.SoapMessages SoapMessages { get; set; }

        /// <summary>
        /// The ProductType to be used in all searches.
        /// </summary>
        ProductType product;

        /// <summary>
        /// The User to be used in all searches.
        /// </summary>
        QualifiedId user;

        /// <summary>
        /// The hpio of the organisation.
        /// </summary>
        QualifiedId hpio;

        /// <summary>
        /// Gets the timestamp for the soap request.
        /// </summary>
        public TimestampType LastSoapRequestTimestamp { get; private set; }

        /// <summary>
        /// HI service name.
        /// </summary>
        public const string HIServiceOperation = "ProviderMatchProviderAdministrativeIndividual";

        /// <summary>
        /// HI service version.
        /// </summary>
        public const string HIServiceVersion = "6.0.0";

        #region Constructors

        /// <summary>
        /// Initializes an instance of the organisation search client.
        /// </summary>
        /// <param name="endpointUri">Web service endpoint for Medicare's organisation search service.</param>
        /// <param name="product">PCIN (generated by Medicare) and platform name values.</param>
        /// <param name="user">Identifier for the application that is calling the service.</param>
        /// <param name="hpio">Identifier for the organisation.</param>
        /// <param name="signingCert">Certificate to sign the soap message with.</param>
        /// <param name="tlsCert">Certificate for establishing TLS connection to the service.</param>
        public ProviderMatchProviderAdministrativeIndividualClient(Uri endpointUri, ProductType product, QualifiedId user, QualifiedId hpio, X509Certificate2 signingCert, X509Certificate2 tlsCert)
        {
            Validation.ValidateArgumentRequired("endpointUri", endpointUri);

            InitializeClient(endpointUri.ToString(), signingCert, tlsCert, product, user, hpio);
        }

        /// <summary>
        /// Initializes an instance of the organisation search client.
        /// </summary>
        /// <param name="endpointUri">Web service endpoint for Medicare's organisation search service.</param>
        /// <param name="product">PCIN (generated by Medicare) and platform name values.</param>
        /// <param name="user">Identifier for the application that is calling the service.</param>
        /// <param name="hpio">Identifier for the organisation.</param>
        /// <param name="signingCert">Certificate to sign the soap message with.</param>
        /// <param name="tlsCert">Certificate for establishing TLS connection to the service.</param>
        /// <param name="initialisationCallback">Callback for additional configuration after creation.</param>
        public ProviderMatchProviderAdministrativeIndividualClient(Uri endpointUri, ProductType product, QualifiedId user, QualifiedId hpio, X509Certificate2 signingCert, X509Certificate2 tlsCert, Action<ServiceEndpoint> initialisationCallback)
        {
            Validation.ValidateArgumentRequired("endpointUri", endpointUri);

            InitializeClient(endpointUri.ToString(), signingCert, tlsCert, product, user, hpio, initialisationCallback);
        }

        #endregion


        public MatchProviderAdministrativeIndividualResponseType MatchProviderAdministrativeInd(MatchProviderAdministrativeIndividualRequestType request)
        {
            //validate


            return MatchProviderAdministrative(request);
        }

        public async Task<MatchProviderAdministrativeIndividualResponseType> MatchProviderAdministrativeIndAsync(MatchProviderAdministrativeIndividualRequestType request)
        {
            //validate

            return await MatchProviderAdministrativeAsync(request);
        }

        /// <summary>
        /// Perform the service call.
        /// </summary>
        /// <param name="request">The search criteria in a MatchProviderAdministrativeIndividualRequestType object.</param>
        /// <returns>The search results in a MatchProviderAdministrativeIndividualResponseType object.</returns>
        private MatchProviderAdministrativeIndividualResponseType MatchProviderAdministrative(MatchProviderAdministrativeIndividualRequestType request)
        {
            matchProviderAdministrativeIndividualRequest envelope = new matchProviderAdministrativeIndividualRequest();

            envelope.matchProviderAdministrativeIndividualRequest1 = request;
            envelope.product = product;
            envelope.user = user;
            envelope.Security = new SecurityHeaderType();
            envelope.timestamp = new TimestampType()
            {
                created = DateTime.Now,
                expires = DateTime.Now.AddDays(30),
                expiresSpecified = true
            };

            // Set LastSoapRequestTimestamp
            LastSoapRequestTimestamp = envelope.timestamp;

            matchProviderAdministrativeIndividualResponse response1 = null;

            try
            {
                response1 = providerMatchProviderAdministrativeIndividualClient.matchProviderAdministrativeInd(envelope);
            }
            catch (Exception ex)
            {
                // Catch generic FaultException and call helper to throw a more specific fault
                // (FaultException<ServiceMessagesType>
                FaultHelper.ProcessAndThrowFault<ServiceMessagesType>(ex);
            }

            if (response1 != null && response1.matchProviderAdministrativeIndividualResponse1 != null)
            {
                return response1.matchProviderAdministrativeIndividualResponse1;
            }
            else
            {
                throw new ApplicationException(Properties.Resources.UnexpectedServiceResponse);
            }
        }

        /// <summary>
        /// Asynchronous implementation of <see cref=" MatchProviderAdministrative" />.
        /// </summary>
        private async Task<MatchProviderAdministrativeIndividualResponseType> MatchProviderAdministrativeAsync(MatchProviderAdministrativeIndividualRequestType request)
        {
            matchProviderAdministrativeIndividualRequest envelope = new matchProviderAdministrativeIndividualRequest();

            envelope.matchProviderAdministrativeIndividualRequest1 = request;
            envelope.product = product;
            envelope.user = user;
            envelope.Security = new SecurityHeaderType();
            envelope.timestamp = new TimestampType()
            {
                created = DateTime.Now,
                expires = DateTime.Now.AddDays(30),
                expiresSpecified = true
            };

            // Set LastSoapRequestTimestamp
            LastSoapRequestTimestamp = envelope.timestamp;

            matchProviderAdministrativeIndividualResponse response1 = null;

            try
            {
                response1 = await providerMatchProviderAdministrativeIndividualClient.matchProviderAdministrativeIndAsync(envelope);
            }
            catch (Exception ex)
            {
                // Catch generic FaultException and call helper to throw a more specific fault
                // (FaultException<ServiceMessagesType>
                FaultHelper.ProcessAndThrowFault<ServiceMessagesType>(ex);
            }

            if (response1 != null && response1.matchProviderAdministrativeIndividualResponse1 != null)
            {
                return response1.matchProviderAdministrativeIndividualResponse1;
            }
            else
            {
                throw new ApplicationException(Properties.Resources.UnexpectedServiceResponse);
            }
        }

        #region Private and internal methods

        /// <summary>
        /// Initialization for the Medicare organisation search client.
        /// </summary>
        /// <param name="endpointUrl">Web service endpoint for the Medicare organisation search.</param>
        /// <param name="signingCert">Certificate to sign the soap message with.</param>
        /// <param name="tlsCert">Certificate for establishing TLS connection to the service.</param>
        /// <param name="product">PCIN (generated by Medicare) and platform name values.</param>
        /// <param name="user">Identifier for the application that is calling the service.</param>
        /// <param name="hpio">Identifier for the organisation</param>
        /// <param name="initialisationCallback">Callback for additional configuration after creation.</param>
        private void InitializeClient(string endpointUrl, X509Certificate2 signingCert, X509Certificate2 tlsCert, ProductType product, QualifiedId user, QualifiedId hpio, Action<ServiceEndpoint> initialisationCallback = null)
        {
            Validation.ValidateArgumentRequired("product", product);
            Validation.ValidateArgumentRequired("user", user);
            Validation.ValidateArgumentRequired("signingCert", signingCert);
            Validation.ValidateArgumentRequired("tlsCert", tlsCert);

            this.product = product;
            this.user = user;
            this.hpio = hpio;

            SoapMessages = new HIEndpointProcessor6.SoapMessages();

            CustomBinding tlsBinding = GetBinding();

            MatchProviderAdministrativeIndividualVirtualPortTypeClient client = null;

            EndpointAddress address = new EndpointAddress(endpointUrl);

            client = new MatchProviderAdministrativeIndividualVirtualPortTypeClient(tlsBinding, address);

            if (client != null)
            {
                HIEndpointProcessor6.SoapMessages soapMessages = new HIEndpointProcessor6.SoapMessages();

                HIEndpointProcessor6.ProcessEndpoint(client.Endpoint, signingCert, SoapMessages);

                if (tlsCert != null)
                {
                    client.ClientCredentials.ClientCertificate.Certificate = tlsCert;
                }

                providerMatchProviderAdministrativeIndividualClient = client;

                initialisationCallback?.Invoke(client.Endpoint);
            }
        }

        /// <summary>
        /// Gets the binding configuration for the client.
        /// </summary>
        /// <returns>Configured customBinding instance.</returns>
        internal CustomBinding GetBinding()
        {
            // Set up binding
            CustomBinding tlsBinding = new CustomBinding();

            TextMessageEncodingBindingElement tlsEncoding = new TextMessageEncodingBindingElement();
            tlsEncoding.ReaderQuotas.MaxDepth = 2147483647;
            tlsEncoding.ReaderQuotas.MaxStringContentLength = 2147483647;
            tlsEncoding.ReaderQuotas.MaxArrayLength = 2147483647;
            tlsEncoding.ReaderQuotas.MaxBytesPerRead = 2147483647;
            tlsEncoding.ReaderQuotas.MaxNameTableCharCount = 2147483647;

            HttpsTransportBindingElement httpsTransport = new HttpsTransportBindingElement();
            httpsTransport.RequireClientCertificate = true;
            httpsTransport.MaxReceivedMessageSize = 2147483647;
            httpsTransport.MaxBufferSize = 2147483647;

            tlsBinding.Elements.Add(tlsEncoding);
            tlsBinding.Elements.Add(httpsTransport);

            return tlsBinding;
        }

        #endregion

        #region IDisposable Members

        /// <summary>
        /// Closes and disposes the client.
        /// </summary>
        public void Dispose()
        {
            ClientBase<MatchProviderAdministrativeIndividualVirtualPortType> lClient;

            if (providerMatchProviderAdministrativeIndividualClient is ClientBase<MatchProviderAdministrativeIndividualVirtualPortType>)
            {
                lClient = (ClientBase<MatchProviderAdministrativeIndividualVirtualPortType>)providerMatchProviderAdministrativeIndividualClient;
                if (lClient.State != CommunicationState.Closed)
                {
                    lClient.Close();
                }
            }
        }

        #endregion
    }
}
