/*
 * Copyright 2011 NEHTA
 *
 * Licensed under the NEHTA Open Source (Apache) License; you may not use this
 * file except in compliance with the License. A copy of the License is in the
 * 'license.txt' file, which should be provided with this work.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

using System;
using System.Threading.Tasks;
using System.ServiceModel.Channels;
using System.Security.Cryptography.X509Certificates;
using System.ServiceModel;
using System.ServiceModel.Description;
using nehta.mcaR32.ProviderReadProviderAdministrativeIndividual;
using Nehta.VendorLibrary.Common;


namespace Nehta.VendorLibrary.HI
{
    /// <summary>
    /// An implementation of a client for the Medicare Healthcare Identifiers service. This class may be used to 
    /// connect to Medicare's service to perform AdministrativeIndividual reads, for provider information already published to the HPD.
    /// </summary>
    public class ProviderReadProviderAdministrativeIndividualClient : IProviderReadProviderAdministrativeIndividualClient
    {
        internal ProviderReadProviderAdministrativeIndividualPortType providerReadProviderAdministrativeIndividualClient;

        /// <summary>
        /// SOAP messages for the last client call.
        /// </summary>
        public HIEndpointProcessor.SoapMessages SoapMessages { get; set; }

        /// <summary>
        /// The ProductType to be used in all searches.
        /// </summary>
        ProductType product;

        /// <summary>
        /// The User to be used in all searches.
        /// </summary>
        QualifiedId user;
        
        /// <summary>
        /// The hpio of the Organisation.
        /// </summary>
        QualifiedId hpio;

        /// <summary>
        /// Gets the timestamp for the soap request.
        /// </summary>
        public TimestampType LastSoapRequestTimestamp { get; private set; }

        /// <summary>
        /// HI service name.
        /// </summary>
        public const string HIServiceOperation = "ProviderReadProviderAdministrativeIndividual";

        /// <summary>
        /// HI service version.
        /// </summary>
        public const string HIServiceVersion = "3.2.0";

        #region Constructors

        /// <summary>
        /// Initializes an instance of the AdministrativeIndividual search client.
        /// </summary>
        /// <param name="endpointUri">Web service endpoint for Medicare's AdministrativeIndividual search service.</param>
        /// <param name="product">PCIN (generated by Medicare) and platform name values.</param>
        /// <param name="user">Identifier for the application that is calling the service.</param>
        /// <param name="hpio">Identifier for the AdministrativeIndividual.</param>
        /// <param name="signingCert">Certificate to sign the soap message with.</param>
        /// <param name="tlsCert">Certificate for establishing TLS connection to the service.</param>
        public ProviderReadProviderAdministrativeIndividualClient(Uri endpointUri, ProductType product, QualifiedId user, QualifiedId hpio, X509Certificate2 signingCert, X509Certificate2 tlsCert)
        {
            Validation.ValidateArgumentRequired("endpointUri", endpointUri);

            InitializeClient(endpointUri.ToString(), signingCert, tlsCert, product, user, hpio);
        }

        /// <summary>
        /// Initializes an instance of the AdministrativeIndividual search client.
        /// </summary>
        /// <param name="endpointUri">Web service endpoint for Medicare's AdministrativeIndividual search service.</param>
        /// <param name="product">PCIN (generated by Medicare) and platform name values.</param>
        /// <param name="user">Identifier for the application that is calling the service.</param>
        /// <param name="hpio">Identifier for the AdministrativeIndividual.</param>
        /// <param name="signingCert">Certificate to sign the soap message with.</param>
        /// <param name="tlsCert">Certificate for establishing TLS connection to the service.</param>
        /// <param name="initialisationCallback">Callback for additional configuration after creation.</param>
        public ProviderReadProviderAdministrativeIndividualClient(Uri endpointUri, ProductType product, QualifiedId user, QualifiedId hpio, X509Certificate2 signingCert, X509Certificate2 tlsCert, Action<ServiceEndpoint> initialisationCallback)
        {
            Validation.ValidateArgumentRequired("endpointUri", endpointUri);

            InitializeClient(endpointUri.ToString(), signingCert, tlsCert, product, user, hpio, initialisationCallback);
        }

        #endregion

        #region Private and internal methods


        /// <summary>
        /// Performs the ReadProviderAdministrativeIndividual call.
        /// </summary>
        /// <param name="request">The request used to perform the ReadProviderAdministrativeIndividual.</param>
        /// <returns>The response returned from the ReadProviderAdministrativeIndividual call.</returns>
        /// <exception cref="ApplicationException">Any exceptions returned from the call.</exception>
        public readProviderAdministrativeIndividualResponse ReadProviderAdministrativeIndividual(readProviderAdministrativeIndividual request)
        {
            var timestamp = new TimestampType
            {
                created = DateTime.Now.ToUniversalTime(),
                expires = DateTime.Now.AddDays(30).ToUniversalTime(),
                expiresSpecified = true
            };

            var readProviderAdministrativeIndividualRequest = new readProviderAdministrativeIndividualRequest(product, new SignatureContainerType(), timestamp, user, hpio, request);


            LastSoapRequestTimestamp = readProviderAdministrativeIndividualRequest.timestamp;

            readProviderAdministrativeIndividualResponse1 response = null;

            try
            {
                response = providerReadProviderAdministrativeIndividualClient.readProviderAdministrativeIndividual(readProviderAdministrativeIndividualRequest);
            }
            catch (Exception ex)
            {
                FaultHelper.ProcessAndThrowFault<ServiceMessagesType>(ex);
            }

            if (response != null && response.readProviderAdministrativeIndividualResponse != null)
                return response.readProviderAdministrativeIndividualResponse;

            throw new ApplicationException(Properties.Resources.UnexpectedServiceResponse);
        }

        /// <summary>
        /// Asynchronous implementation of <see cref=" ReadProviderAdministrativeIndividual" />.
        /// </summary>
        public async Task<readProviderAdministrativeIndividualResponse> ReadProviderAdministrativeIndividualAsync(readProviderAdministrativeIndividual request)
        {
            var timestamp = new TimestampType
            {
                created = DateTime.Now.ToUniversalTime(),
                expires = DateTime.Now.AddDays(30).ToUniversalTime(),
                expiresSpecified = true
            };

            var readProviderAdministrativeIndividualRequest = new readProviderAdministrativeIndividualRequest(product, new SignatureContainerType(), timestamp, user, hpio, request);


            LastSoapRequestTimestamp = readProviderAdministrativeIndividualRequest.timestamp;

            readProviderAdministrativeIndividualResponse1 response = null;

            try
            {
                response = await providerReadProviderAdministrativeIndividualClient.readProviderAdministrativeIndividualAsync(readProviderAdministrativeIndividualRequest);
            }
            catch (Exception ex)
            {
                FaultHelper.ProcessAndThrowFault<ServiceMessagesType>(ex);
            }

            if (response != null && response.readProviderAdministrativeIndividualResponse != null)
                return response.readProviderAdministrativeIndividualResponse;

            throw new ApplicationException(Properties.Resources.UnexpectedServiceResponse);
        }

        /// <summary>
        /// Initialization for the Medicare AdministrativeIndividual search client.
        /// </summary>
        /// <param name="endpointUrl">Web service endpoint for the Medicare AdministrativeIndividual search.</param>
        /// <param name="signingCert">Certificate to sign the soap message with.</param>
        /// <param name="tlsCert">Certificate for establishing TLS connection to the service.</param>
        /// <param name="product">PCIN (generated by Medicare) and platform name values.</param>
        /// <param name="user">Identifier for the application that is calling the service.</param>
        /// <param name="initialisationCallback">Callback for additional configuration after creation.</param>
        private void InitializeClient(string endpointUrl, X509Certificate2 signingCert, X509Certificate2 tlsCert, ProductType product, QualifiedId user, QualifiedId hpio, Action<ServiceEndpoint> initialisationCallback = null)
        {
            Validation.ValidateArgumentRequired("product", product);
            Validation.ValidateArgumentRequired("user", user);
            Validation.ValidateArgumentRequired("signingCert", signingCert);
            Validation.ValidateArgumentRequired("tlsCert", tlsCert);

            this.product = product;
            this.user = user;
            this.hpio = hpio;

            SoapMessages = new HIEndpointProcessor.SoapMessages();

            CustomBinding tlsBinding = GetBinding();

            ProviderReadProviderAdministrativeIndividualPortTypeClient client = null;

            EndpointAddress address = new EndpointAddress(endpointUrl);

            client = new ProviderReadProviderAdministrativeIndividualPortTypeClient(tlsBinding, address);

            if (client != null)
            {
                HIEndpointProcessor.ProcessEndpoint(client.Endpoint, signingCert, SoapMessages);

                if (tlsCert != null) client.ClientCredentials.ClientCertificate.Certificate = tlsCert;
                
                providerReadProviderAdministrativeIndividualClient = client;

                initialisationCallback?.Invoke(client.Endpoint);
            }
        }

        /// <summary>
        /// Gets the binding configuration for the client.
        /// </summary>
        /// <returns>Configured customBinding instance.</returns>
        internal CustomBinding GetBinding()
        {
            // Set up binding
            CustomBinding tlsBinding = new CustomBinding();

            TextMessageEncodingBindingElement tlsEncoding = new TextMessageEncodingBindingElement();
            tlsEncoding.ReaderQuotas.MaxDepth = 2147483647;
            tlsEncoding.ReaderQuotas.MaxStringContentLength = 2147483647;
            tlsEncoding.ReaderQuotas.MaxArrayLength = 2147483647;
            tlsEncoding.ReaderQuotas.MaxBytesPerRead = 2147483647;
            tlsEncoding.ReaderQuotas.MaxNameTableCharCount = 2147483647;

            HttpsTransportBindingElement httpsTransport = new HttpsTransportBindingElement();
            httpsTransport.RequireClientCertificate = true;
            httpsTransport.MaxReceivedMessageSize = 2147483647;
            httpsTransport.MaxBufferSize = 2147483647;

            tlsBinding.Elements.Add(tlsEncoding);
            tlsBinding.Elements.Add(httpsTransport);

            return tlsBinding;
        }

        #endregion

        #region IDisposable Members

        /// <summary>
        /// Closes and disposes the client.
        /// </summary>
        public void Dispose()
        {
            ClientBase<ProviderReadProviderAdministrativeIndividualPortType> lClient;

            if (providerReadProviderAdministrativeIndividualClient is ClientBase<ProviderReadProviderAdministrativeIndividualPortType>)
            {
                lClient = (ClientBase<ProviderReadProviderAdministrativeIndividualPortType>)providerReadProviderAdministrativeIndividualClient;
                if (lClient.State != CommunicationState.Closed)
                    lClient.Close();
            }
        }

        #endregion
    }
}
